/* i18n.js — tiny synchronous i18n runtime for the study site.
 *
 * Language dictionaries are plain JS objects registered by lang/<code>.js
 * (loaded as <script> tags BEFORE this file is used, but AFTER this file
 * defines window.I18N). Keys are flat, dotted strings; values are the
 * user-facing text for that language.
 *
 * Resolution order for t(key):
 *   1. current language dict (if key present AND non-empty)
 *   2. English dict (en) as fallback
 *   3. the literal `fallback` arg, else the key itself
 *
 * Components re-render on language change because SiteApp keeps `lang` in
 * React state and calls I18N.set(); see site-app.jsx.
 *
 * Translation agents: DO NOT edit this file. Edit lang/fr.js and lang/tr.js.
 * See TRANSLATION_GUIDE.md for the full convention (slots, proper nouns…).
 */
(function () {
  "use strict";

  const SUPPORTED = ["en", "fr", "tr"];
  const NAMES = { en: "English", fr: "Français", tr: "Türkçe" };
  const STORE = "facadeLang_v1";

  const dicts = { en: {}, fr: {}, tr: {} };
  const listeners = new Set();

  let lang = "en";
  try {
    const saved = localStorage.getItem(STORE);
    if (saved && SUPPORTED.includes(saved)) lang = saved;
  } catch (e) { /* private mode / blocked storage */ }

  function t(key, fallback) {
    const d = dicts[lang];
    if (d && d[key] != null && d[key] !== "") return d[key];
    const en = dicts.en;
    if (en && en[key] != null && en[key] !== "") return en[key];
    return fallback != null ? fallback : key;
  }

  /* Split a string on a {slot} placeholder and re-join with a node in its
   * place. Used for sentences that contain an emphasized / styled word, so
   * the word can be translated separately while staying positioned in the
   * sentence. Returns an array safe to render in JSX.
   * e.g. tSlot("Can a webcam feel {x}?", "x", <em>fear</em>) */
  function tSlot(str, slot, node) {
    const token = "{" + slot + "}";
    const i = str.indexOf(token);
    if (i < 0) return [str];
    return [str.slice(0, i), node, str.slice(i + token.length)];
  }

  window.I18N = {
    SUPPORTED,
    NAMES,
    get lang() { return lang; },
    set(l) {
      if (!SUPPORTED.includes(l) || l === lang) return;
      lang = l;
      try { localStorage.setItem(STORE, l); } catch (e) { /* ignore */ }
      try { document.documentElement.setAttribute("lang", l); } catch (e) { /* ignore */ }
      listeners.forEach((fn) => fn(l));
    },
    t,
    tSlot,
    onChange(fn) { listeners.add(fn); return () => listeners.delete(fn); },
    _register(code, dict) {
      if (!dicts[code]) dicts[code] = {};
      Object.assign(dicts[code], dict);
    },
  };

  try { document.documentElement.setAttribute("lang", lang); } catch (e) { /* ignore */ }
})();
