/* site-data.js — builds window.SITE.
 *
 * Translatable prose is resolved from the i18n dictionaries (lang/*.js) via
 * t(); non-text fields (ids, numbers, CSS keys, FSM state names, config
 * strings, formula tokens) stay literal. window.SITE is rebuilt on language
 * change so switching re-renders translated content (SiteApp re-renders too).
 *
 * Translation agents: do NOT edit this file — translate the `data.*` keys in
 * lang/*.js. Sessions, numbers, and code-ish tokens are intentionally literal.
 */
(function () {
  "use strict";

  function buildSite() {
    const t = window.I18N.t;

    // 7 real presentation sessions (from Pipeline/presentation/*/meta.json)
    const SESSIONS = [
      { id: "S06_Vid16", subject: "S06", vid: "Vid16", lighting: "bright", dur: 876, videoWidth: 290, videoHeight: 240, events: 11, note: t("data.sess.S06_Vid16.note") },
      { id: "S02_Vid04", subject: "S02", vid: "Vid04", lighting: "dim",    dur: 598, videoWidth: 200, videoHeight: 240, events: 14, note: t("data.sess.S02_Vid04.note") },
      { id: "S08_Vid18", subject: "S08", vid: "Vid18", lighting: "mixed",  dur: 275, videoWidth: 480, videoHeight: 320, events: 17, note: t("data.sess.S08_Vid18.note") },
      { id: "S04_Vid09", subject: "S04", vid: "Vid09", lighting: "bright", dur: 504, videoWidth: 240, videoHeight: 260, events: 9,  note: t("data.sess.S04_Vid09.note") },
      { id: "S05_Vid10", subject: "S05", vid: "Vid10", lighting: "bright", dur: 343, videoWidth: 270, videoHeight: 260, events: 12, note: t("data.sess.S05_Vid10.note") },
      { id: "S10_Vid13", subject: "S10", vid: "Vid13", lighting: "bright", dur: 425, videoWidth: 220, videoHeight: 210, events: 13, note: t("data.sess.S10_Vid13.note") },
    ];

    // headline outcomes — REAL numbers from the final report (§6.6, abstract)
    const RESULTS = [
      { k: t("data.results.0.k"), v: "0.77", s: t("data.results.0.s"), tone: "accent" },
      { k: t("data.results.1.k"), v: "53", unit: "ms", s: t("data.results.1.s"), tone: "clear" },
      { k: t("data.results.2.k"), v: "99.9", unit: "%", s: t("data.results.2.s"), tone: "" },
      { k: t("data.results.3.k"), v: "6 · 88", s: t("data.results.3.s"), tone: "" },
    ];

    const FUSE = {
      f12: { tag: "F12", name: t("data.fuse.f12.name"), thr: 0.70,
             eq: [t("data.fuse.f12.eq0"), t("data.fuse.f12.eq1")] },
      f15: { tag: "F15", name: t("data.fuse.f15.name"), thr: 0.80,
             eq: [t("data.fuse.f15.eq0"), t("data.fuse.f15.eq1")] },
    };

    // teaching cases for the F12 vs F15 page (faithful to the fusion logic)
    const TEACH = [
      {
        key: "false", tab: t("data.teach.0.tab"),
        title: t("data.teach.0.title"),
        fear: 0.64, arousal: 0.22, tension: 0.16, bpmRise: 0.02,
        f12Why: t("data.teach.0.f12Why"),
        f15Why: t("data.teach.0.f15Why"),
      },
      {
        key: "true", tab: t("data.teach.1.tab"),
        title: t("data.teach.1.title"),
        fear: 0.72, arousal: 0.66, tension: 0.25, bpmRise: 0.26,
        f12Why: t("data.teach.1.f12Why"),
        f15Why: t("data.teach.1.f15Why"),
      },
    ];

    const METHODS = [
      { ic: "lighting", t: t("data.methods.0.t"), p: t("data.methods.0.p") },
      { ic: "contrast", t: t("data.methods.1.t"), p: t("data.methods.1.p") },
      { ic: "fuse",     t: t("data.methods.2.t"), p: t("data.methods.2.p") },
      { ic: "pulse",    t: t("data.methods.3.t"), p: t("data.methods.3.p") },
    ];

    // ── PIPELINE stages (architecture flow, §5.1) ──
    const PIPELINE = [
      { k: "01", t: t("data.pipeline.0.t"), s: t("data.pipeline.0.s"), d: t("data.pipeline.0.d"), tag: "input" },
      { k: "02", t: t("data.pipeline.1.t"), s: t("data.pipeline.1.s"), d: t("data.pipeline.1.d"), tag: "pre" },
      { k: "03", t: t("data.pipeline.2.t"), s: t("data.pipeline.2.s"), d: t("data.pipeline.2.d"), tag: "pre" },
      { k: "04", t: t("data.pipeline.3.t"), s: t("data.pipeline.3.s"), d: t("data.pipeline.3.d"), tag: "face" },
      { k: "05", t: t("data.pipeline.4.t"), s: t("data.pipeline.4.s"), d: t("data.pipeline.4.d"), tag: "body" },
      { k: "06", t: t("data.pipeline.5.t"), s: t("data.pipeline.5.s"), d: t("data.pipeline.5.d"), tag: "fuse" },
      { k: "07", t: t("data.pipeline.6.t"), s: t("data.pipeline.6.s"), d: t("data.pipeline.6.d"), tag: "fuse" },
      { k: "08", t: t("data.pipeline.7.t"), s: t("data.pipeline.7.s"), d: t("data.pipeline.7.d"), tag: "out" },
    ];

    // ── research questions (§1) ──
    const RQS = [
      { id: "RQ1", q: t("data.rqs.0.q"), a: t("data.rqs.0.a"), status: "answered" },
      { id: "RQ2", q: t("data.rqs.1.q"), a: t("data.rqs.1.a"), status: "partial" },
      { id: "RQ3", q: t("data.rqs.2.q"), a: t("data.rqs.2.a"), status: "open" },
    ];

    // ── key findings (§6.6) ──
    const FINDINGS = [
      { n: "01", t: t("data.findings.0.t"), p: t("data.findings.0.p") },
      { n: "02", t: t("data.findings.1.t"), p: t("data.findings.1.p") },
      { n: "03", t: t("data.findings.2.t"), p: t("data.findings.2.p") },
      { n: "04", t: t("data.findings.3.t"), p: t("data.findings.3.p") },
      { n: "05", t: t("data.findings.4.t"), p: t("data.findings.4.p") },
    ];

    // FER asymmetry (§7.1) — standalone F1 of each tool
    const ASYMMETRY = {
      detector:  { name: "HSEmotion", sub: t("data.asym.detector.sub"), f1: 0.67, role: t("data.asym.detector.role"), note: t("data.asym.detector.note") },
      amplifier: { name: "MediaPipe", sub: t("data.asym.amplifier.sub"), f1: 0.065, role: t("data.asym.amplifier.role"), note: t("data.asym.amplifier.note") },
    };

    // rPPG augmentation sweep best configs (Table 6.8)
    const RPPG_CONFIGS = [
      { cfg: "POS @ 30s / 3s", c: 0.5, p: 90.0, r: 66.7, f1: 0.766, best: true,  why: t("data.rppg.0.why") },
      { cfg: "POS @ 10s / 2s", c: 1.0, p: 81.2, r: 72.2, f1: 0.765, best: false, why: t("data.rppg.1.why") },
      { cfg: "POS @ 10s / 5s", c: 0.8, p: 85.0, r: 63.0, f1: 0.740, best: false, why: t("data.rppg.2.why") },
    ];

    // ── THE GAME (§5.8) ──
    const ENEMIES = [
      {
        key: "wanderer", name: "Le Rôdeur", aka: t("data.enemies.wanderer.aka"), cls: t("data.enemies.wanderer.cls"),
        fsm: ["WANDER", "ALERT", "CHASE", "POUNCE", "COOLDOWN"],
        channels: [
          { t: t("data.enemies.wanderer.ch0.t"), d: t("data.enemies.wanderer.ch0.d") },
          { t: t("data.enemies.wanderer.ch1.t"), d: t("data.enemies.wanderer.ch1.d") },
          { t: t("data.enemies.wanderer.ch2.t"), d: t("data.enemies.wanderer.ch2.d") },
        ],
        accent: "danger",
      },
      {
        key: "watcher", name: "Le Veilleur", aka: t("data.enemies.watcher.aka"), cls: t("data.enemies.watcher.cls"),
        fsm: ["IDLE", "APPEAR", "FROZEN / DESPAWN / STRIKE"],
        matrix: [
          { see: t("data.enemies.watcher.m0.see"), calm: t("data.enemies.watcher.m0.calm"), afraid: t("data.enemies.watcher.m0.afraid") },
          { see: t("data.enemies.watcher.m1.see"), calm: t("data.enemies.watcher.m1.calm"), afraid: t("data.enemies.watcher.m1.afraid") },
        ],
        channels: [
          { t: t("data.enemies.watcher.ch0.t"), d: t("data.enemies.watcher.ch0.d") },
          { t: t("data.enemies.watcher.ch1.t"), d: t("data.enemies.watcher.ch1.d") },
          { t: t("data.enemies.watcher.ch2.t"), d: t("data.enemies.watcher.ch2.d") },
        ],
        accent: "moon",
      },
    ];

    // ── DESIGN PATH (the three-bullet arc; game = 3rd, hit by hardware) ──
    const PATH = [
      { n: "01", t: t("data.path.0.t"), state: "shipped",   meta: t("data.path.0.meta"), d: t("data.path.0.d") },
      { n: "02", t: t("data.path.1.t"), state: "shipped",   meta: t("data.path.1.meta"), d: t("data.path.1.d") },
      { n: "03", t: t("data.path.2.t"), state: "disrupted", meta: t("data.path.2.meta"), d: t("data.path.2.d") },
    ];

    window.SITE = { SESSIONS, RESULTS, FUSE, TEACH, METHODS, PIPELINE, RQS, FINDINGS, ASYMMETRY, RPPG_CONFIGS, ENEMIES, PATH };
  }

  buildSite();
  window.I18N.onChange(buildSite);
})();
